name: BuildNewCommits

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare Matrix
    runs-on: ubuntu-latest
        
    outputs:
      versions: ${{ steps.load_countries.outputs.versions }}
      
    steps:
      - name: Install BC Container Helper
        shell: pwsh   
        run: Install-Module bccontainerhelper -force

      - name: Check out the repository to the runner
        uses: actions/checkout@v4.1.2
        with:
          ref: main
      
      - name: Load Countries and Versions
        id: load_countries
        shell: pwsh       
        run: ./Scripts/GetVersions.ps1

      - name: ShowOutput      
        shell: pwsh       
        run: Write-Host '${{ steps.load_countries.outputs.versions }}'
        
  buildCommits:
    needs: prepare
    name: Update NuGet
    runs-on: windows-latest
    
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.versions) }}

    steps:
      - name: Install BC Container Helper
        shell: pwsh   
        run: Install-Module bccontainerhelper -force

      - name: Check out the repository to the runner
        uses: actions/checkout@v4.2.1
        
      - name: Update NuGet
        shell: pwsh       
        run: |
          ./Scripts/BCNuGetArtifacts.ps1 -Country ${{matrix.versions.country}} -Select ${{matrix.versions.version}}

